# Generated by Django 5.0.4 on 2024-04-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink',
            new_name='drink_name',
        ),
    ]
